"""init

Revision ID: 86953d20e230
Revises: 
Create Date: 2025-06-07 15:40:13.297899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86953d20e230'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklists',
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern')
    )
    op.create_table('channelhistorys',
    sa.Column('channel_link', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('channel_link', sa.String(), nullable=False),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_link')
    )
    op.create_table('posts',
    sa.Column('check_date', sa.DateTime(), nullable=False),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.Column('channel_link', sa.String(), nullable=False),
    sa.Column('post_link', sa.String(), nullable=False),
    sa.Column('post_text', sa.String(), nullable=True),
    sa.Column('user_requested', sa.Integer(), nullable=True),
    sa.Column('is_recipe', sa.Boolean(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_link'),
    sa.UniqueConstraint('post_link')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('channels')
    op.drop_table('channelhistorys')
    op.drop_table('blacklists')
    # ### end Alembic commands ###
